# author = "Protesilaos Stavrou (https://protesilaos.com)"
# description = "Dark theme with a palette inspired by winter nights at the city (WCAG AA compliant)"
# name = "Tempus Winter"

[colors.bright]
black = "#2a2e38"
blue = "#329fcb"
cyan = "#1ba6a4"
green = "#00ab5f"
magenta = "#ca77c5"
red = "#de7b28"
white = "#8da3b8"
yellow = "#af9155"

[colors.cursor]
cursor = "#8da3b8"
text = "#202427"

[colors.normal]
black = "#202427"
blue = "#7b91df"
cyan = "#4fa394"
green = "#4aa920"
magenta = "#d17e80"
red = "#ed6e5a"
white = "#91959b"
yellow = "#9a9921"

[colors.primary]
background = "#202427"
foreground = "#8da3b8"

[colors.selection]
background = "#8da3b8"
text = "#202427"
